//
// Copyright 2026 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
#ifndef PXR_IMAGING_PLUGIN_HD_EMBREE_DISPLACEMENT_H
#define PXR_IMAGING_PLUGIN_HD_EMBREE_DISPLACEMENT_H

#include "pxr/pxr.h"

#include <embree4/rtcore_geometry.h>

PXR_NAMESPACE_OPEN_SCOPE

/// Evaluate a MaterialXCpp displacement terminal for vertices generated by
/// Embree subdivision. This is an Embree callback rather than ordinary surface
/// shading because only Embree knows the final tessellated vertex positions.
void HdEmbreeDisplacementFunction(
    const RTCDisplacementFunctionNArguments* args);

PXR_NAMESPACE_CLOSE_SCOPE

#endif
