//
// Copyright 2016 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//

#include "pxr/pxr.h"

#include "pxr/base/tf/pyEnum.h"

#include "pxr/base/arch/demangle.h"
#include "pxr/base/tf/diagnostic.h"
#include "pxr/base/tf/instantiateSingleton.h"
#include "pxr/base/tf/iterator.h"
#include "pxr/base/tf/mallocTag.h"
#include "pxr/base/tf/pyWrapContext.h"
#include "pxr/base/tf/stringUtils.h"

#include <algorithm>
#include <cstring>
#include <iterator>

PXR_NAMESPACE_OPEN_SCOPE

TF_INSTANTIATE_SINGLETON(Tf_PyEnumRegistry);

using std::string;

Tf_PyEnumRegistry::Tf_PyEnumRegistry()
    : _unknownValueFactory(nullptr)
    , _pythonConvertersRegistered(false)
{
}

// CODE_COVERAGE_OFF No way to destroy the enum registry currently.
Tf_PyEnumRegistry::~Tf_PyEnumRegistry()
{
    // release our references on all the objects we own.
    TF_FOR_ALL(i, _objectsToEnums)
        Py_DECREF(i->first);
}
// CODE_COVERAGE_ON

PyObject *
Tf_PyEnumRegistry::ConvertEnumToPython(TfEnum const &e)
{
    // If there is no registered enum object, create a new one of the
    // appropriate type.
    if (!_enumsToObjects.count(e)) {
        if (!_unknownValueFactory) {
            PyErr_SetString(
                PyExc_RuntimeError,
                "No Python enum object factory has been registered.");
            return nullptr;
        }

        std::string name = ArchGetDemangled(e.GetType());
        name = TfStringReplace(name, " ", "_");
        name = TfStringReplace(name, "::", "_");
        name = TfStringReplace(name, "<", "_");
        name = TfStringReplace(name, ">", "_");
        name = "AutoGenerated_" + name + "_" + TfStringify(e.GetValueAsInt());

        PyObject *wrappedVal = _unknownValueFactory(name, e);
        if (!wrappedVal) {
            return nullptr;
        }

        RegisterValue(e, wrappedVal);
        Py_DECREF(wrappedVal);
    }

    PyObject *obj = _enumsToObjects[e];
    Py_INCREF(obj);
    return obj;
}

static string
_GetStringAttr(PyObject *obj, const char *attrName)
{
    PyObject *attr = PyObject_GetAttrString(obj, attrName);
    if (!attr) {
        return string();
    }

    const char *value = PyUnicode_AsUTF8(attr);
    string result = value ? value : string();
    Py_DECREF(attr);
    return result;
}

string
Tf_PyEnumRepr(PyObject *self) {
    string moduleName = _GetStringAttr(self, "__module__");
    string baseName = _GetStringAttr(self, "_baseName");
    string name = _GetStringAttr(self, "name");

    return TfStringGetSuffix(moduleName) + "." +
        (baseName.empty() ? string() : baseName + ".") +
        name;
}

// Returns true if name is a Python keyword and cannot be used as an
// identifier. This encompasses keywords from both Python 2 and 3 so
// that enum names don't change depending on the version of Python
// being used.
static bool
_IsPythonKeyword(const std::string& name)
{
    static const char* _PythonKeywords[] = {
        "False", "None", "True", "and", "as", "assert",
        "async", "await", "break", "class", "continue", "def",
        "del", "elif", "else", "except", "exec", "finally",
        "for", "from", "global", "if", "import", "in",
        "is", "lambda", "nonlocal", "not", "or", "pass",
        "print", "raise", "return", "try", "while", "with",
        "yield"
    };

    TF_DEV_AXIOM(std::is_sorted(
        std::begin(_PythonKeywords), std::end(_PythonKeywords),
        [](const char* x, const char* y) { return strcmp(x, y) < 0; }));

    return std::binary_search(
        std::begin(_PythonKeywords), std::end(_PythonKeywords), name);
}

string Tf_PyCleanEnumName(string name, bool stripPackageName)
{
    if (stripPackageName) {
        const string pkgName =
            Tf_PyWrapContextManager::GetInstance().GetCurrentContext();
        if (TfStringStartsWith(name, pkgName) && name != pkgName) {
            name.erase(0, pkgName.size());
        }
    }

    if (_IsPythonKeyword(name)) {
        name += "_";
    }

    return TfStringReplace(name, " ", "_");
}

void Tf_PyEnumAddAttribute(PyObject *scope,
                           const std::string &name,
                           PyObject *value) {
    // Skip exporting attr if the scope already has an attribute
    // with that name, but do make sure to place it in .allValues
    // for the class.
    if (PyObject_HasAttrString(scope, name.c_str())) {
        TF_CODING_ERROR(
            "Ignoring enum value '%s'; an attribute with that "
            "name already exists in that scope.", name.c_str());
    }
    else {
        PyObject_SetAttrString(scope, name.c_str(), value);
    }
}

void
Tf_PyEnumRegistry::
RegisterValue(TfEnum const &e, PyObject *obj)
{
    TfAutoMallocTag2 tag("Tf", "Tf_PyEnumRegistry::RegisterValue");

    // we take a reference to obj.
    Py_INCREF(obj);

    _enumsToObjects[e] = obj;
    _objectsToEnums[obj] = e;
}

bool
Tf_PyEnumRegistry::
FindEnumForPythonObject(PyObject *obj, TfEnum *e) const
{
    TfHashMap<PyObject *, TfEnum, _ObjectHash>::const_iterator i =
        _objectsToEnums.find(obj);
    if (i == _objectsToEnums.end()) {
        return false;
    }

    if (e) {
        *e = i->second;
    }
    return true;
}

void
Tf_PyEnumRegistry::
SetUnknownValueFactory(UnknownValueFactory factory)
{
    _unknownValueFactory = factory;
}

bool
Tf_PyEnumRegistry::
MarkPythonConvertersRegistered()
{
    if (_pythonConvertersRegistered) {
        return false;
    }

    _pythonConvertersRegistered = true;
    return true;
}

PXR_NAMESPACE_CLOSE_SCOPE
